import { Zap, Target, Brain, Puzzle, Settings, Shield } from "lucide-react";
import ankiCard from "@/assets/anki-card.jpg";

const Features = () => {
  const features = [
    {
      icon: Zap,
      title: "Lightning Fast",
      description: "Create perfect flashcards in under 2 seconds. No more breaking your study flow."
    },
    {
      icon: Target,
      title: "Context-Aware",
      description: "Automatically finds the best example sentences from trusted Japanese corpora."
    },
    {
      icon: Brain,
      title: "Smart Recognition",
      description: "Handles both kanji and kana search with automatic furigana generation."
    },
    {
      icon: Puzzle,
      title: "Perfect Integration",
      description: "Seamlessly syncs with your existing Anki decks and respects your tags and preferences."
    },
    {
      icon: Settings,
      title: "Fully Customizable",
      description: "Adapt card templates to match your personal study style and learning goals."
    },
    {
      icon: Shield,
      title: "Privacy First",
      description: "All processing happens locally. Your learning data never leaves your browser."
    }
  ];

  return (
    <section id="features" className="py-24 bg-muted/30">
      <div className="container mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl lg:text-5xl font-bold mb-6">
            Everything you need to{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              master Japanese
            </span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            From click to flashcard in seconds. Soku handles all the tedious work so you can focus on what matters most: learning.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-16 items-center mb-16">
          {/* Features list */}
          <div className="grid md:grid-cols-2 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="group p-6 bg-gradient-card border border-border rounded-xl shadow-card hover:shadow-glow transition-all duration-300">
                <div className="w-12 h-12 bg-gradient-primary rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300">
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </div>
            ))}
          </div>

          {/* Anki card showcase */}
          <div className="relative">
            <div className="relative">
              <img 
                src={ankiCard} 
                alt="Example Anki flashcard generated by Soku"
                className="w-full h-auto rounded-2xl shadow-card border border-border/50"
              />
              <div className="absolute inset-0 bg-gradient-primary opacity-20 rounded-2xl blur-xl -z-10" />
            </div>
            <div className="absolute -bottom-6 -right-6 bg-accent text-accent-foreground px-4 py-2 rounded-full font-semibold text-sm shadow-button">
              Auto-generated in 1.8s
            </div>
          </div>
        </div>

        {/* Stats */}
        <div className="grid md:grid-cols-4 gap-8 text-center">
          {[
            { number: "10,000+", label: "Active Users" },
            { number: "500K+", label: "Cards Created" },
            { number: "1.8s", label: "Average Speed" },
            { number: "99.2%", label: "Accuracy Rate" }
          ].map((stat, index) => (
            <div key={index} className="p-6 bg-gradient-card border border-border rounded-xl shadow-card">
              <div className="text-3xl font-bold bg-gradient-primary bg-clip-text text-transparent mb-2">
                {stat.number}
              </div>
              <div className="text-muted-foreground">{stat.label}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;